### ISSUE TITLE
Dropdown Component [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [thekavikumar/love-simple-ui#10]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by thekavikumar** [comment]
Sure @Sukhendu2002

**Comment by Sukhendu2002** [comment]
Hey @thekavikumar I added 4 kinds of dropdowns, do you want me to add more

- Normal Dropdown
- Dropdown on hover
- Dropdown with icon
- Dropdown with search

![image](https://github.com/thekavikumar/love-simple-ui/assets/76804228/74a6bd3e-2b3f-4e48-b340-c2c6a0965943)
![image](https://github.com/thekavikumar/love-simple-ui/assets/76804228/fde8cc95-2799-4c71-a0d9-b9788e752079)
![image](https://github.com/thekavikumar/love-simple-ui/assets/76804228/dd024efc-c48d-46bd-8fc6-ac01932338f9)

**Comment by thekavikumar** [comment]
@Sukhendu2002 your wish you can contribute more!
