### ISSUE TITLE
[Docs] README.md 

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [thekavikumar/love-simple-ui#101]
* Upon reviewing the contribution steps outlined in the README.md file, I have identified room for improvement. Kindly assign me the task, as I am confident in my ability to enhance the quality of the steps.

**Comment by thekavikumar** [comment]
Sure!

**Comment by Shiva-Sai-ssb** [comment]
> Sure!

Thank you for assigning me this task. I assure you that I will diligently work towards enhancing the steps involved.
