### ISSUE TITLE
Add dark mode toggle 

### ISSUE THREAD

**Issue by khushi1711** [thekavikumar/love-simple-ui#102]
for seamless view of website and as per users comfort .will try to add toggle for dark view mode.
assign this issue to me.
i'm GSSOC'23 contributor

**Comment by karananu** [comment]
assign this issue to me.
i'm GSSOC'23 contributor

**Comment by PatilHarshh** [comment]
@thekavikumar please assign this project to me

**Comment by AyushPathak7074** [comment]
for seamless view of website and as per users comfort .will try to add toggle for dark view mode.
assign this issue to me.
i'm GSSOC'23 contributor

**Comment by karananu** [comment]
I will do it by tomorrow my laptop was corrupted

**Comment by tab21** [comment]
Hey I would like to work on this issue, please can this be assigned to me?

**Comment by thekavikumar** [comment]
Please make sure everyone creates toggles with different styles
