### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by RashakDude** [thekavikumar/love-simple-ui#104]
### Current Behavior
I am thinking of a lightweight date picker component

### Desired Behavior
By clicking the input box, you can select a date from a popup calendar.

### Screenshots / Mockups
![Image](https://github.com/thekavikumar/love-simple-ui/assets/45696541/a8f596b0-1c7d-4ed8-a2a8-7ad62b3250e3)

**Comment by RashakDude** [comment]
@thekavikumar

**Comment by afreen061** [comment]
I would like to work on this please assign it to me @thekavikumar
