### ISSUE TITLE
Circular Progress Bar

### ISSUE THREAD

**Issue by RashakDude** [thekavikumar/love-simple-ui#107]
### Current Behavior
Display the current progress of an operation flow.

### Desired Behavior
If it will take a long time to complete an operation, you can use Progress to show the current progress and status.

- When an operation will interrupt the current interface, or it needs to run in the background for more than 2 seconds.
- When you need to display the completion percentage of an operation.

### Screenshots / Mockups
![68747470733a2f2f692e696d6775722e636f6d2f58665a69684c772e706e67](https://github.com/thekavikumar/love-simple-ui/assets/45696541/2e5d95af-eb82-43e3-b887-6afc1cfbf525)

**Comment by RashakDude** [comment]
@thekavikumar

**Comment by Visbhavesh** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.
