### ISSUE TITLE
Create Attracting Readme.txt

### ISSUE THREAD

**Issue by Cdggtt** [thekavikumar/love-simple-ui#11]
In my point of view in readme.txt add Pic of the websites and Installing process of the Love Simple UI

**Comment by Cdggtt** [comment]
Getting started 4th paragraph
We have developers in mind! 😊 love-simple-ui is designed to be developer-friendly, providing you with a seamless and enjoyable experience. Our intuitive API and comprehensive documentation make it a breeze to get started and create stunning user interfaces. Whether you're building a simple web app or a complex enterprise application, love-simple-ui has got your back! 💙

Instead of this we changes
We have developer as a top priority! love-simple-ui is designed to be developer-friendly, furnishing you with a seamless and enjoyable experience. Our intuitive API and comprehensive documentation make it a breeze to get started and create stunning user interfaces. Whether you're fabricating a straightforward web application or an intricate venture application , love-simple-ui has got your back! 💙

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.
