### ISSUE TITLE
Add loading button

### ISSUE THREAD

**Issue by Abhinavcode13** [thekavikumar/love-simple-ui#117]
### Current Behavior
To add a new UI component - loading button

### Desired Behavior
The button starts in an enabled state, allowing the user to interact with it.
When the button is clicked, it enters a loading state to indicate that an action is in progress.
The button becomes disabled to prevent further clicks while the action is being processed.
The button displays a loading indicator or custom loading text to provide visual feedback to the user.
After the action is completed, the button returns to its enabled state, allowing for further interactions.

### Screenshots / Mockups
![image](https://github.com/thekavikumar/love-simple-ui/assets/126642111/36b1f7ea-926c-4a22-a9ab-e18e3a75c418)

---

**Comment by Abhinavcode13** [comment]
Its great to have a material UI repo , I have already worked on material UI components. great job

can you assign me this @thekavikumar

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?

**Comment by thekavikumar** [comment]
This issue is resolved!
Pls contribute to some other issue
Happy coding
