### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by praharshaAdhikari** [thekavikumar/love-simple-ui#14]
I would like to be assigned to create a stylish search bar component. [GSSoC'23]

**Comment by thekavikumar** [comment]
Sure!

**Comment by PatilHarshh** [comment]
Hi I would love to work upon it @thekavikumar

**Comment by venkataraviraja5** [comment]
can u please assign to me @thekavikumar

**Comment by vk20july** [comment]
@thekavikumar I want to work on this issue under gssoc'23
