### ISSUE TITLE
Navbar UI component 

### ISSUE THREAD

**Issue by Abhinavcode13** [thekavikumar/love-simple-ui#144]
### Current Behavior

ADD Navbar UI component 

### Desired Behavior

A navbar UI component, also known as a navigation bar or menu bar, is a user interface element that provides navigation and menu options for users to navigate through different sections or pages of a website or application. It typically appears at the top of a webpage or screen and acts as a centralized hub for accessing various functionalities.

---

**Comment by rimi0602** [comment]
I'd like to contribute as well.

**Comment by thekavikumar** [comment]
rimi pls create another issue, I will assign u to it

**Comment by swayamshreenanda20** [comment]
Hi,
I would like to work on this issue under gssoc'23,
Can you assign it to me?

**Comment by iamparas0** [comment]
if this not done yet please assign it to me.
