### ISSUE TITLE
Alert components with different type

### ISSUE THREAD

**Issue by Deepanshu0703** [thekavikumar/love-simple-ui#17]
I would like to be assigned to create a alerts with cross and after some time vansishes functionality I have already some PR regarding this issue. It has various types.[GSSoC'2023]

**Comment by thekavikumar** [comment]
Make sure to use some other style! because there is a pr with the idea

**Comment by thekavikumar** [comment]
Okay nevermind, that's you who created the pr

**Comment by Deepanshu0703** [comment]
yes I have created that PR already and raise the issue now
