### ISSUE TITLE
Landing Page for the website

### ISSUE THREAD

**Issue by ojasaklechayt** [thekavikumar/love-simple-ui#170]
I want to work on the following feature under GSSOC'23.

### Current Behavior
Currently the website shows " Website will be up soon "

### Desired Behavior
Adding a beautiful, simple and responsive landing page for the website. Also wants to configure the use of tailwind in the site folder were.

### Screenshots / Mockups
Current Behavior:
![image](https://github.com/thekavikumar/love-simple-ui/assets/90605717/fe60184b-73f3-4eca-b165-45f4cd2a8a08)

Expected Behavior:
![image](https://github.com/thekavikumar/love-simple-ui/assets/90605717/733cbd45-15ca-47b9-916c-161ec251b22b)

---

**Comment by ojasaklechayt** [comment]
@thekavikumar ser can you please assign this to me. I have designed this and I can make this landing page. In future we can also add navbar to it and can expand the website.

**Comment by thekavikumar** [comment]
sure
