### ISSUE TITLE
Login/Signup Using Google

### ISSUE THREAD

**Issue by code-soubhik** [thekavikumar/love-simple-ui#173]
### Current Behavior
If I want to log in, I must have an account for that I need to Signup means I need to fill out the signup page 
We can enhance the UX by adding a feature i.e. Login or Signup using Google.

### Desired Behavior
Login or Signup with one click using Google will be there on the login and signup page.
If you want I also can add many more apps like Facebook or Twitter

### Screenshots / Mockups
![Screenshot 2023-06-27 020358](https://github.com/thekavikumar/love-simple-ui/assets/90599826/039f887f-423d-494e-88e5-0caa2e00ca1f)

---

**Comment by soubhik-111** [comment]
@thekavikumar Can you provide me google Client ID,
Once you assign me this task

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by Uma-Shankar0927** [comment]
Can I work on it?
