### ISSUE TITLE
Feedback Form Component

### ISSUE THREAD

**Issue by hima-v** [thekavikumar/love-simple-ui#177]
### Current Behavior
There are many ways of communicating with the customers, one of them is by taking a survey.
Google Forms are effective mode of submitting information. This feature can be added.

### Desired Behavior
The google form would be integrated with the website itself, and it would follow the website's theme.
I have worked on one such feature for a project, below is the mockup.

### Screenshots / Mockups
![image](https://github.com/thekavikumar/love-simple-ui/assets/79623293/fc5f10da-c901-434b-8de8-658a9d88c35c)

---
I want to work on this as a GSSoC'23 Contributor.

**Comment by shreyaspathak11** [comment]
Assign me this task
