### ISSUE TITLE
Make a Name logo of the site

### ISSUE THREAD

**Issue by Tisha6661** [thekavikumar/love-simple-ui#178]
### Current Behavior
currently there is no logo, whereas logo enhances the look of the website.

### Desired Behavior
I wish to contribute in making the logo of the site.

### Screenshots / Mockups
Here are some examples-
![Screenshot 2023-06-24 005041](https://github.com/thekavikumar/love-simple-ui/assets/98682478/4da4d202-0648-4730-82a4-bcf6fee6007b)
![Screenshot 2023-06-27 011300](https://github.com/thekavikumar/love-simple-ui/assets/98682478/e27c621b-2bb7-46db-8d0c-64cd27a0b21a)
![image](https://github.com/thekavikumar/love-simple-ui/assets/98682478/b0720279-e521-41af-b8c2-4c05a2676b96)

---

**Comment by Tisha6661** [comment]
@thekavikumar Why did you close this issue? I've made the logo-

![Screenshot 2023-06-29 000158](https://github.com/thekavikumar/love-simple-ui/assets/98682478/71ac48ef-f21e-4b02-91fb-5e9e50da8386)
but didn't fix it in the code yet

**Comment by Tisha6661** [comment]
I see you have uploaded the logo in a changed font, but please give me this chance, I have done a lot of work to come up with the design, and I can redesign if you don't like this.

**Comment by thekavikumar** [comment]
This won't be fitting for the navbar, find a logo with icon and name in a row. 
See the logo that I have on my website in simple and neat. Like that something you can come up

**Comment by Tisha6661** [comment]
@thekavikumar Sure I understand, I will make the logo as you suggested.

**Comment by Tisha6661** [comment]
@thekavikumar I have made a pull request for this task, please verify.
