### ISSUE TITLE
[Add] Illustration images or videos of components 

### ISSUE THREAD

**Issue by apneduniya** [thekavikumar/love-simple-ui#18]
As a developer, we would love if it would have some illustration or the result of the components in the documentation in the form of videos or images as it will provide a basic idea of what your components give and also if the components is fullfilling the developers need 💖.

I want to do this for you 🙂.

**Comment by thekavikumar** [comment]
Cool @apneduniya

**Comment by apneduniya** [comment]
Hey, I can't find the website code? In which I would add the images in it.

**Comment by thekavikumar** [comment]
@apneduniya  [Repo](https://github.com/thekavikumar/love-simple-ui-docs)

**Comment by apneduniya** [comment]
Will it be considered in GSSOC 🤔, whatever I would contribute to the documentation 🙂.

**Comment by thekavikumar** [comment]
Yup, as both the repo are the same project
