### ISSUE TITLE
CREATE A NICE FAVICON FOR THE WEBSITE

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/love-simple-ui#193]

**Comment by Killer2OP** [comment]
@thekavikumar Can you assign me this issue.

**Comment by thekavikumar** [comment]
Sure! Done

**Comment by thekavikumar** [comment]
https://nextra.site/docs use this for ref

**Comment by Killer2OP** [comment]
> https://nextra.site/docs use this for ref

okie :)

**Comment by thekavikumar** [comment]
Also, try to change the theme of the website, I mean just the colors ( max combination of 1 or 2 colors) ( don't make it more colorful)

**Comment by thekavikumar** [comment]
Put a msg in that issue

**Comment by Killer2OP** [comment]
> Put a msg in that issue

ok

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
