### ISSUE TITLE
Write tests for the components

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/love-simple-ui#196]

**Comment by shraddha761** [comment]
@thekavikumar assign this issue to  me

**Comment by thekavikumar** [comment]
unit tests using jest lib

**Comment by Killer2OP** [comment]
I can create the test code using but where to put those test files??

**Comment by shraddha761** [comment]
> individual file will be better

OK ,
Then I can do that and will put those test files in a separate folder.
If this is alright assign me this issue :)

**Comment by Killer2OP** [comment]
Ok,
Then I can do that and will create a separate folder in which all the test files will be.
If this is alright Assign me the issue :)

**Comment by thekavikumar** [comment]
Okay sure
