### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by shraddha761** [thekavikumar/love-simple-ui#210]
### Current Behavior
A component that divides content into separate pages, allowing users to navigate through them, commonly used for long lists or tables.

### Desired Behavior
When users interact with the Pagination component, they can click on a specific page number to navigate directly to that page. Alternatively, they can use the "Previous" and "Next" buttons to move to the adjacent pages.

Assign this issue to me under GSSOC'23

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
