### ISSUE TITLE
Request to Add Hover Effects to Social Links

### ISSUE THREAD

**Issue by Yashika-Agrawal** [thekavikumar/love-simple-ui#219]
### Current Behavior
![image](https://github.com/thekavikumar/love-simple-ui/assets/97408966/dd279cf6-9d1e-4bbc-a511-a4adb254a7f8)
I would like to contribute to the project by adding hover effects to the social links. Currently, the social links lack interactivity, and I believe adding hover effects would enhance the user experience and make the links more visually appealing.

### Desired Behavior
When hovering over the social links, I propose adding a subtle hover effect such as changing the background color, adding a shadow,  to provide visual feedback and make the links more engaging.

**Comment by Yashika-Agrawal** [comment]
@thekavikumar , Please assign me this issue under GSSOC'23 contribution.

**Comment by Aastha7078** [comment]
can u assign this to me
