### ISSUE TITLE
To increase the size of dark/light mode button

### ISSUE THREAD

**Issue by Yashika-Agrawal** [thekavikumar/love-simple-ui#220]
### Current Behavior

I would like to contribute to the project by suggesting an improvement to the dark/light mode button. Currently, the button is small and not very visible, especially in the bottom left corner. I believe increasing the size of the button would make it more prominent and improve the accessibility and usability of the feature.

### Desired Behavior
By increasing the size of the dark/light mode button, I propose to make it more visible and accessible, allowing users to switch between modes effortlessly. The larger size will enhance the button's clickability and improve the overall user experience.

### Screenshots / Mockups
![image](https://github.com/thekavikumar/love-simple-ui/assets/97408966/57221ce3-2b58-4f43-bf9b-df695918aae0)

---

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
