### ISSUE TITLE
Hover Effect

### ISSUE THREAD

**Issue by Harshu467** [thekavikumar/love-simple-ui#225]
### Current Behavior

As of now when hover on icon their is hover effect and also with npm package , but not with github and twitter
### Desired Behavior

When u create navbar , u try to be consistent, hover features must be consistence from left to right. Hence I want to create effect of hover to twitter and github so webiste looks more pretty and standard with consistence 
### Screenshots / Mockups

![image](https://github.com/thekavikumar/love-simple-ui/assets/89975347/30fcce70-ff69-43ac-924d-f976e8b1b76b)

---

**Comment by Harshu467** [comment]
Assign it to me I am GSOC 23 contributor. Add labels of GSOC and level 1 @thekavikumar

**Comment by Kajal2468** [comment]
I want to work on the issue please assign this issue in under GSSoc'23.

Thank you!

**Comment by Harshu467** [comment]
Thanks to @thekavikumar  for merging , Issue it resolved , I am closing it
