### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by Harshu467** [thekavikumar/love-simple-ui#226]
### Current Behavior

As of now we have default scrollbar color, When u create a website , u try to make things matchable to theme colors. As of now we have default scrollbar . We can Add custom scrollbar
### Desired Behavior

I will try to add custom scrollbar with size and with custom color.It makes website more standard and attractive , user-friendly design
### Screenshots / Mockups

![image](https://github.com/thekavikumar/love-simple-ui/assets/89975347/5690aab8-4bc0-416c-a67a-86d1def91b2f)

---

**Comment by Harshu467** [comment]
Assign it to me I am GSOC 23 contributor. Add labels of GSOC and level 1 @thekavikumar

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by Harshu467** [comment]
> please assign me this issue i will solve under GSSOC'23

Check or create other issues.

**Comment by Harshu467** [comment]
@thekavikumar Assign it to me
