### ISSUE TITLE
Urgent Bug Remove

### ISSUE THREAD

**Issue by Harshu467** [thekavikumar/love-simple-ui#228]
### Description

Need to update .gitignore. As of now evry time user install npm every local machine has its own package-lock.json , when user push , it also goes in branch and it causes various issues.
### Expected Behavior

Update .gitignore file to add package-lock.json
### Screenshots

![image](https://github.com/thekavikumar/love-simple-ui/assets/89975347/5df75d6c-61b0-465d-a1f8-d6031bb33464)
![image](https://github.com/thekavikumar/love-simple-ui/assets/89975347/ef2869c9-dd26-4b89-b873-46ed732ec353)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by Harshu467** [comment]
@thekavikumar  Please assign it to me
