### ISSUE TITLE
Bug in edit this page button

### ISSUE THREAD

**Issue by sumitkr2000** [thekavikumar/love-simple-ui#27]
Hey @thekavikumar there is a bug in edit this page link. I want to remove the bug. Please sign me this issue. Thank you!

**Comment by sumitkr2000** [comment]
@thekavikumar can you please tell me what is required to show when a user clicks the link?

**Comment by thekavikumar** [comment]
github repo of it

**Comment by sumitkr2000** [comment]
ok cool thank you fo letting me know.

**Comment by sumitkr2000** [comment]
@thekavikumar i cant find the html file can u please tell why it is not there?

**Comment by thekavikumar** [comment]
it is fully made by markdown! @sumitkr2000

**Comment by sumitkr2000** [comment]
Ohh sorry i didn't realised that 😂

**Comment by thekavikumar** [comment]
no prob

**Comment by sumitkr2000** [comment]
@thekavikumar bro I am not able to find the md file of the homepage. can you please help me?
