### ISSUE TITLE
Create Footer UI Component

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/love-simple-ui#3]
Create a footer UI component with its types!
Make sure you use the typescript properly!

**Comment by vk20july** [comment]
I want to work on this issue under GSSoc 23

**Comment by MukulsinghRajpurohit** [comment]
@thekavikumar  would you like to assign this issue to me . actually i was working on this footer component

**Comment by thekavikumar** [comment]
@MukulsinghRajpurohit  You can also work on this!

**Comment by MukulsinghRajpurohit** [comment]
ok thanks

**Comment by PayalPadmalyaPrusty** [comment]
@thekavikumar I want to contribute.Please assign me

**Comment by KhushiKhandelwal610** [comment]
@thekavikumar I would also like to contribute on this issue. Please assign me to it.

**Comment by vk20july** [comment]
sir @thekavikumar can you tell me which person PR will merge if more than one persons are assign?

**Comment by thekavikumar** [comment]
people will have different styles and due to that everyone's will be merged

**Comment by vk20july** [comment]
ok sir
