### ISSUE TITLE
scrolling effect while clicking on Love Simple UI

### ISSUE THREAD

**Issue by Sanju-Gautam0855** [thekavikumar/love-simple-ui#34]
When we are scrolling to the end of the website and click on the Love Simple UI, it abruptly changes to the beginning of the page. If there will be a smooth back-scrolling effect that comes back to the beginning from the part we are now, it will show how many parts we have read on a quick basis.
@thekavikumar kindly assign me this issue.

**Comment by thekavikumar** [comment]
Sure

**Comment by vk20july** [comment]
I want to work on this issue under GSSOC 23

**Comment by thekavikumar** [comment]
@vk20july  please select some other issue or create a new issue! this is already assigned

**Comment by vk20july** [comment]
ok sir

**Comment by Sanju-Gautam0855** [comment]
@thekavikumar sir, I want to ask if I can use react because you have used only typescript.

**Comment by thekavikumar** [comment]
@Sanju-Gautam0855  please learn typescript and this is a 3month program, you can learn stuffs and implement too

**Comment by vk20july** [comment]
> @Sanju-Gautam0855 please learn typescript and this is a 3month program, you can learn stuffs and implement too

sir i know typescript concept can you assign this issue to me?

**Comment by Sanju-Gautam0855** [comment]
@thekavikumar sir I can work on my project. I ask about react because this was written under the website's link.

**Comment by Sanju-Gautam0855** [comment]
@vk20july please do some other issue

**Comment by vk20july** [comment]
Ok
