### ISSUE TITLE
New Components are welcomed!

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/love-simple-ui#4]

**Comment by JatinBisht2308** [comment]
Sir I am creating a testimonials sort of corousel should I start working on it, from GSSoC 23 sir.

**Comment by thekavikumar** [comment]
@JatinBisht2308 Sure start working on it!

**Comment by aashish-aanand** [comment]
I will move contact section to the footer and will add social media button at the footer with hover effect, shall I start working on it.

**Comment by thekavikumar** [comment]
This project doesn't have footer yet, can you explain little clear @aashish-aanand

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by JatinBisht2308** [comment]
@adityavpawar create your own issue this is already assigned to me.

**Comment by saiwali** [comment]
Hello, @thekavikumar I have experience with the technologies needed to add beautiful UI components. I would like to work on this issue. Could you assign this issue to me ??

**Comment by thekavikumar** [comment]
@saiwali  please create a issue with the name of your component as the title

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by thekavikumar** [comment]
@rafiya2003 pls create a new issue with the title of the components you are gonna create

**Comment by Visbhavesh** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.
