### ISSUE TITLE
Create a loader component

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [thekavikumar/love-simple-ui#40]
I would like to work on this component. Please assign me to it.

**Comment by An525ish** [comment]
it would help if you assign it under the gssoc tag

**Comment by KhushiKhandelwal610** [comment]
I am a part of GSSOC'23

**Comment by KhushiKhandelwal610** [comment]
Please assign me it under GSSOC'23

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me.
@thekavikumar

**Comment by PatilHarshh** [comment]
@thekavikumar  thank you you are very kind
Please give me deadline

**Comment by thekavikumar** [comment]
@PatilHarshh  take your time, there is no deadline

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I would like to work upon this issue.
