### ISSUE TITLE
Bug at the center of the footer 

### ISSUE THREAD

**Issue by bhaskarkumar1** [thekavikumar/love-simple-ui#44]
Please assign me the task to center the footer content of the website  for larger screen. As it is not in the center of the screen as we can see in the screeshot attached below
![footer](https://github.com/thekavikumar/love-simple-ui/assets/84345649/a0836b67-fefa-4fc8-b173-dc59901f429e)

**Comment by bhaskarkumar1** [comment]
Ok thank you for assigning it to me. I will work on it.

**Comment by vk20july** [comment]
@thekavikumar I want to work on this issue under gssoc'23
