### ISSUE TITLE
Proposal to make modal components with diffrent style

### ISSUE THREAD

**Issue by BhavyaMPatel** [thekavikumar/love-simple-ui#47]
I would like to create modal component with diifrent styles
pls assign this issue to me

**Comment by BhavyaMPatel** [comment]
and yes kindly please tell could I use tailwind css ?

**Comment by BhavyaMPatel** [comment]
Thank you for assigne me

**Comment by thekavikumar** [comment]
@BhavyaMPatel  you have to use only styled-components by goober.js

**Comment by BhavyaMPatel** [comment]
ohk thank you understood
