### ISSUE TITLE
Adding Accordion component

### ISSUE THREAD

**Issue by Sameep002** [thekavikumar/love-simple-ui#49]
i want to contribute with accordion component in your project

**Comment by thekavikumar** [comment]
Why did you close?

**Comment by Sameep002** [comment]
i can create accordion component which takes title and content as parameter, but i dont know how to make it in typescript format.

**Comment by thekavikumar** [comment]
@Sameep002 it is very similar to how you create components in react, just you have to define types for it. 
Learn typescript it will be easy if you know react

**Comment by Sameep002** [comment]
@thekavikumar alright then assign it to me, will work on it 👍
