### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [thekavikumar/love-simple-ui#63]
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by sumitkr2000** [comment]
Hey @thekavikumar It seems the that he is not active. It's been 1 month now. Can you assign me this issue, please?

**Comment by sumitkr2000** [comment]
Hey, @thekavikumar Lazy loading can not be implemented in your website because right now your website is not completed. There are only components present in the repository. Please remind me once the website is completed. Thank you and sorry for the inconvenience.
