### ISSUE TITLE
Creating a Docs Website with Next JS

### ISSUE THREAD

**Issue by thekavikumar** [thekavikumar/love-simple-ui#75]

**Comment by kisshan13** [comment]
Yeah I'm up for this issue 🤟

**Comment by naveeng2402** [comment]
I'm in

**Comment by saharshg29** [comment]
why next js and not react??

**Comment by kisshan13** [comment]
in react we have to manually handle the routings and all, here we will get everything done

**Comment by sandygudie** [comment]
Hi, a suggestion for the documentation
We could use [docusarus](https://docusaurus.io/)

**Comment by thekavikumar** [comment]
@sandygudie  yeah we can use that, please msg it in the discord channel so that others also can give their suggestions on this
