### ISSUE TITLE
[Docs] add contributors graph

### ISSUE THREAD

**Issue by S-ishita** [thekavikumar/love-simple-ui#76]
### Desired State:

--- I want to add contributors graph in readme.PLease assign this issue to me under GSSOC

**Comment by thekavikumar** [comment]
Sure!

**Comment by thekavikumar** [comment]
@S-ishita  Make sure you take the project role from self-roles channel

**Comment by S-ishita** [comment]
> @S-ishita Make sure you take the project role from self-roles channel

Done already :)
