### ISSUE TITLE
NavBar Component

### ISSUE THREAD

**Issue by Soura700** [thekavikumar/love-simple-ui#8]

**Comment by PayalPadmalyaPrusty** [comment]
@Soura700 I want to contribute.Please assign me

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue.
