### ISSUE TITLE
Error in Button Folder

### ISSUE THREAD

**Issue by AditiSingh2003** [thekavikumar/love-simple-ui#80]
### Description
While running the program in terminal it is throwing error

### Expected Behavior
Website to run properly

### Screenshots
![Screenshot (25)](https://github.com/thekavikumar/love-simple-ui/assets/97729662/f5f7b09f-cf21-4a1c-9b34-c18d1be21d8b)

**Comment by kisshan13** [comment]
yea just remove the imports and exports for LoadingButton component in index.ts , we removed the component for a issue

**Comment by aadityadike** [comment]
@AditiSingh2003  i am facing exact same issue.

**Comment by kisshan13** [comment]
[love-simple-ui.vercel.app](https://love-simple-ui.vercel.app/) This one? , well we're working on the site and it'll get live asap.

to run ```bash npm run ladle```

**Comment by aadityadike** [comment]
> 
@AditiSingh2003 
are you working on this issue? if not i would like to take it.

**Comment by AditiSingh2003** [comment]
I am currently working and had almost solved the issue.

**Comment by aadityadike** [comment]
Fine
