### ISSUE TITLE
Enhance dark mode option

### ISSUE THREAD

**Issue by gaur15** [thekavikumar/love-simple-ui#81]
### Current Behavior
It doesn't show dark mode option 

### Desired Behavior
 dark option is required because it reduces blue light exposure

### Screenshots / Mockups

---

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by gaur15** [comment]
![Screenshot (1)](https://github.com/thekavikumar/love-simple-ui/assets/133087361/e352985d-74ac-4294-8624-2f4cf19ff3c0)
sir I'm not able to make changes and see changes because of this .I will complete my issue as soon as this page opens up
