### ISSUE TITLE
Carousels Component

### ISSUE THREAD

**Issue by Krishi1211** [thekavikumar/love-simple-ui#9]
Adding a new Carousels component

**Comment by PayalPadmalyaPrusty** [comment]
@Krishi1211 I want to contribute.Please assign me

**Comment by thekavikumar** [comment]
@PayalPadmalyaPrusty  You can add another carousel component with a different style, So please create another issue and I'll assign it to you!

**Comment by khushiminda** [comment]
as a ui.ux designer i find your ui is a little not up to the mark
i can make a carousel effect for yourr website to show various cool transitions
i can add coolest transitions


Please assign me this issue under gssoc 23 so that i can submit the PR

**Comment by khushiminda** [comment]
Thankyou so much I'll work on this
