### ISSUE TITLE
Bug: Your page is down 

### ISSUE THREAD

**Issue by bhaskarkumar1** [thekavikumar/love-simple-ui#92]
### Description

See the screenshot
### Screenshots

![page down](https://github.com/thekavikumar/love-simple-ui/assets/84345649/ba503959-e3a8-406e-8ec7-d9ea9831cc1b)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

**Comment by thekavikumar** [comment]
@bhaskarkumar1 Actually we are creating a new website, and will be up next week!
