### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by ayushtiwari110** [thekavikumar/love-simple-ui#96]
Hello, I would like to update the readme badges with more better UI (rounded corners), and also do some enhancements to the readme file to make it more visually appealing. kindly assign this issue to me.
[GSSOC'23]

**Comment by thekavikumar** [comment]
@ayushtiwari110  Sure!

**Comment by ayushtiwari110** [comment]
Thanks for assigning!

**Comment by ayushtiwari110** [comment]
hey! @thekavikumar , I looked at the readme file and did some changes which might make it look better. I have done the changes and initiated a PR, kindly check. 
Thanks for your time!

**Comment by ayushtiwari110** [comment]
Hey There! Since my PR has been merged successfully, I am closing this issue as completed.
Nice time working on it!
